server:
  port: 8080
  servlet:
    context-path: /demo
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: 1230489dg9f0fsdf23423sdfgsr23
  lifetime: 30m
spring:
  data:
    jpa:
      repositories:
        enabled: true
        base-package: com.sbertesttask.ticktacktoe.repository
  liquibase:
    drop-first: true
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  datasource:
    driver-class-name: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true